vich_uploader:
    db_driver: orm

    mappings:
        equipe_images:
            uri_prefix: /images/equipe
            upload_destination: '%kernel.project_dir%/public/images/equipe'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
